<!DOCTYPE html>
<html>
	<head>
	<link rel="stylesheet" href="/public/css/bootstrap.css">
	<link rel="stylesheet" href="/public/css/style.css">
	<script src="/public/js/jquery-1.7.2.min.js"></script>
	</head>
	<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a href="#" class="brand">C 2102 v1</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    <div class="container content-container">
	<div class="row">
		<!-- Main -->
		<div class="span8">
			<?php echo $this->layout()->content; ?>
		</div>
		<!-- Side Bar -->
		<div class="span4">
		Side bar here
		</div>
	</div>
      
</div>
	
	</body>
</html>
